version: '3.3'

services:
  postgres:
    image: postgres:13
    environment:
      - POSTGRES_DB=localMarket
      - POSTGRES_USER=localmarket
      - POSTGRES_PASSWORD=localMarketAOK2024
    ports:
      - 5432:5432
    volumes:
      - ./postgres_data:/var/lib/postgresql/data

  pgadmin:
    image: dpage/pgadmin4
    environment:
      - PGADMIN_DEFAULT_EMAIL=localmarket@mail.com
      - PGADMIN_DEFAULT_PASSWORD=localMarketAOK2024
    ports:
      - 5050:80



